# Generated by Django 6.0.2 on 2026-02-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('album', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(max_length=10)),
                ('lang', models.CharField(choices=[('tamil', 'Tamil'), ('malayalam', 'Malayalam'), ('hindi', 'Hindi'), ('english', 'English')], default='tamil', max_length=50)),
                ('audio_url', models.URLField(max_length=1000)),
                ('cover_image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
