# Generated by Django 6.0.2 on 2026-02-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lang',
            field=models.CharField(choices=[('tamil', 'Tamil'), ('malayalam', 'Malayalam'), ('hindi', 'Hindi'), ('english', 'English')], default='tamil', max_length=50),
        ),
    ]
